package com.hmsjuan.conversordemonedas.herramientas;

import java.util.HashMap;

public class Monedas {
    public HashMap<String, String> listaMonedas = new HashMap<>();
    public void llenarMonedas() {
        listaMonedas.put("AED", "Dirham de los Emiratos Árabes Unidos");
        listaMonedas.put("AFN", "Afgani afgano");
        listaMonedas.put("ALL", "Lek albanés");
        listaMonedas.put("AMD", "Dram armenio");
        listaMonedas.put("ANG", "Florín antillano neerlandés");
        listaMonedas.put("AOA", "Kwanza angoleño");
        listaMonedas.put("ARS", "Peso argentino");
        listaMonedas.put("AUD", "Dólar australiano");
        listaMonedas.put("AWG", "Florín arubeño");
        listaMonedas.put("AZN", "Manat azerbaiyano");
        listaMonedas.put("BAM", "Marco convertible de Bosnia-Herzegovina");
        listaMonedas.put("BBD", "Dólar de Barbados");
        listaMonedas.put("BDT", "Taka bangladesí");
        listaMonedas.put("BGN", "Lev búlgaro");
        listaMonedas.put("BHD", "Dinar bahreiní");
        listaMonedas.put("BIF", "Franco burundés");
        listaMonedas.put("BMD", "Dólar bermudeño");
        listaMonedas.put("BND", "Dólar de Brunéi");
        listaMonedas.put("BOB", "Boliviano boliviano");
        listaMonedas.put("BRL", "Real brasileño");
        listaMonedas.put("BSD", "Dólar bahameño");
        listaMonedas.put("BTN", "Ngultrum butanés");
        listaMonedas.put("BWP", "Pula botsuano");
        listaMonedas.put("BYN", "Rublo bielorruso");
        listaMonedas.put("BZD", "Dólar beliceño");
        listaMonedas.put("CAD", "Dólar canadiense");
        listaMonedas.put("CDF", "Franco congoleño");
        listaMonedas.put("CHF", "Franco suizo");
        listaMonedas.put("CLP", "Peso chileno");
        listaMonedas.put("CNY", "Yuan chino");
        listaMonedas.put("COP", "Peso colombiano");
        listaMonedas.put("CRC", "Colón costarricense");
        listaMonedas.put("CUP", "Peso cubano");
        listaMonedas.put("CVE", "Escudo caboverdiano");
        listaMonedas.put("CZK", "Corona checa");
        listaMonedas.put("DJF", "Franco yibutiano");
        listaMonedas.put("DKK", "Corona danesa");
        listaMonedas.put("DOP", "Peso dominicano");
        listaMonedas.put("DZD", "Dinar argelino");
        listaMonedas.put("EGP", "Libra egipcia");
        listaMonedas.put("ERN", "Nakfa eritreo");
        listaMonedas.put("ETB", "Birr etíope");
        listaMonedas.put("EUR", "Euro");
        listaMonedas.put("FJD", "Dólar fiyiano");
        listaMonedas.put("FKP", "Libra de las Islas Malvinas");
        listaMonedas.put("FOK", "Króna feroesa");
        listaMonedas.put("GBP", "Libra esterlina");
        listaMonedas.put("GEL", "Lari georgiano");
        listaMonedas.put("GGP", "Libra de Guernsey");
        listaMonedas.put("GHS", "Cedi ghanés");
        listaMonedas.put("GIP", "Libra de Gibraltar");
        listaMonedas.put("GMD", "Dalasi gambiano");
        listaMonedas.put("GNF", "Franco guineano");
        listaMonedas.put("GTQ", "Quetzal guatemalteco");
        listaMonedas.put("GYD", "Dólar guyanés");
        listaMonedas.put("HKD", "Dólar de Hong Kong");
        listaMonedas.put("HNL", "Lempira hondureño");
        listaMonedas.put("HRK", "Kuna croata");
        listaMonedas.put("HTG", "Gourde haitiano");
        listaMonedas.put("HUF", "Forinto húngaro");
        listaMonedas.put("IDR", "Rupia indonesia");
        listaMonedas.put("ILS", "Nuevo séquel israelí");
        listaMonedas.put("IMP", "Libra de la Isla de Man");
        listaMonedas.put("INR", "Rupia india");
        listaMonedas.put("IQD", "Dinar iraquí");
        listaMonedas.put("IRR", "Rial iraní");
        listaMonedas.put("ISK", "Corona islandesa");
        listaMonedas.put("JEP", "Libra de Jersey");
        listaMonedas.put("JMD", "Dólar jamaicano");
        listaMonedas.put("JOD", "Dinar jordano");
        listaMonedas.put("JPY", "Yen japonés");
        listaMonedas.put("KES", "Chelín keniano");
        listaMonedas.put("KGS", "Som kirguís");
        listaMonedas.put("KHR", "Riel camboyano");
        listaMonedas.put("KID", "Dólar de Kiribati");
        listaMonedas.put("KMF", "Franco comorense");
        listaMonedas.put("KPW", "Won norcoreano");
        listaMonedas.put("KRW", "Won surcoreano");
        listaMonedas.put("KWD", "Dinar kuwaití");
        listaMonedas.put("KYD", "Dólar de las Islas Caimán");
        listaMonedas.put("KZT", "Tenge kazajo");
        listaMonedas.put("LAK", "Kip laosiano");
        listaMonedas.put("LBP", "Libra libanesa");
        listaMonedas.put("LKR", "Rupia de Sri Lanka");
        listaMonedas.put("LRD", "Dólar liberiano");
        listaMonedas.put("LSL", "Loti lesothense");
        listaMonedas.put("LYD", "Dinar libio");
        listaMonedas.put("MAD", "Dirham marroquí");
        listaMonedas.put("MDL", "Leu moldavo");
        listaMonedas.put("MGA", "Ariary malgache");
        listaMonedas.put("MKD", "Denar macedonio");
        listaMonedas.put("MMK", "Kyat birmano");
        listaMonedas.put("MNT", "Tugrik mongol");
        listaMonedas.put("MOP", "Pataca macaense");
        listaMonedas.put("MRU", "Uguia mauritana");
        listaMonedas.put("MUR", "Rupia mauriciana");
        listaMonedas.put("MVR", "Rufiyaa maldiva");
        listaMonedas.put("MWK", "Kwacha malauí");
        listaMonedas.put("MXN", "Peso mexicano");
        listaMonedas.put("MYR", "Ringgit malayo");
        listaMonedas.put("MZN", "Metical mozambiqueño");
        listaMonedas.put("NAD", "Dólar namibio");
        listaMonedas.put("NGN", "Naira nigeriano");
        listaMonedas.put("NIO", "Córdoba nicaragüense");
        listaMonedas.put("NOK", "Corona noruega");
        listaMonedas.put("NPR", "Rupia nepalesa");
        listaMonedas.put("NZD", "Dólar neozelandés");
        listaMonedas.put("OMR", "Rial omaní");
        listaMonedas.put("PAB", "Balboa panameño");
        listaMonedas.put("PEN", "Sol peruano");
        listaMonedas.put("PGK", "Kina de Papúa Nueva Guinea");
        listaMonedas.put("PHP", "Peso filipino");
        listaMonedas.put("PKR", "Rupia paquistaní");
        listaMonedas.put("PLN", "Zloty polaco");
        listaMonedas.put("PYG", "Guaraní paraguayo");
        listaMonedas.put("QAR", "Rial qatarí");
        listaMonedas.put("RON", "Leu rumano");
        listaMonedas.put("RSD", "Dinar serbio");
        listaMonedas.put("RUB", "Rublo ruso");
        listaMonedas.put("RWF", "Franco ruandés");
        listaMonedas.put("SAR", "Rial saudí");
        listaMonedas.put("SBD", "Dólar de las Islas Salomón");
        listaMonedas.put("SCR", "Rupia seychelense");
        listaMonedas.put("SDG", "Libra sudanesa");
        listaMonedas.put("SEK", "Corona sueca");
        listaMonedas.put("SGD", "Dólar de Singapur");
        listaMonedas.put("SHP", "Libra de Santa Elena");
        listaMonedas.put("SLL", "Leone de Sierra Leona");
        listaMonedas.put("SOS", "Chelín somalí");
        listaMonedas.put("SRD", "Dólar surinamés");
        listaMonedas.put("SSP", "Libra sursudanesa");
        listaMonedas.put("STN", "Dobra santotomense");
        listaMonedas.put("SYP", "Libra siria");
        listaMonedas.put("SZL", "Lilangeni suazi");
        listaMonedas.put("THB", "Baht tailandés");
        listaMonedas.put("TJS", "Somoni tayiko");
        listaMonedas.put("TMT", "Manat turcomano");
        listaMonedas.put("TND", "Dinar tunecino");
        listaMonedas.put("TOP", "Pa'anga tongano");
        listaMonedas.put("TRY", "Lira turca");
        listaMonedas.put("TTD", "Dólar de Trinidad y Tobago");
        listaMonedas.put("TVD", "Dólar tuvaluano");
        listaMonedas.put("TWD", "Nuevo dólar taiwanés");
        listaMonedas.put("TZS", "Chelín tanzano");
        listaMonedas.put("UAH", "Grivna ucraniana");
        listaMonedas.put("UGX", "Chelín ugandés");
        listaMonedas.put("USD", "Dólar estadounidense");
        listaMonedas.put("UYU", "Peso uruguayo");
        listaMonedas.put("UZS", "Som uzbeko");
        listaMonedas.put("VES", "Bolívar venezolano");
        listaMonedas.put("VND", "Dong vietnamita");
        listaMonedas.put("VUV", "Vatu vanuatuense");
        listaMonedas.put("WST", "Tala samoano");
        listaMonedas.put("XAF", "Franco CFA de África Central");
        listaMonedas.put("XCD", "Dólar del Caribe Oriental");
        listaMonedas.put("XDR", "Derechos especiales de giro");
        listaMonedas.put("XOF", "Franco CFA de África Occidental");
        listaMonedas.put("XPF", "Franco CFP");
        listaMonedas.put("YER", "Rial yemení");
        listaMonedas.put("ZAR", "Rand sudafricano");
        listaMonedas.put("ZMW", "Kwacha zambiano");
        listaMonedas.put("ZWL", "Dólar zimbabuense");


    }


}
